issue: 3
categories:
  course-automation:
    - demo/contributions/course-automation/*/*
  presentation:
    - demo/contributions/course-automation/week[1-9]/*/*
  demo:
    - demo/contributions/demo/*/*
  essay:
    - demo/contributions/essay/*/*
  executable-tutorial:
    - demo/contributions/executable-tutorial/*/*
  feedback:
    - demo/contributions/feedback/*/*
  open-source:
    - demo/contributions/open-source/*/*
