name: 'PR Validator'
description: 'Action that validated each proposal and assigns the appropriate labels to it'
inputs:
  github-token:
    description: 'A valid GitHub token with acces to the repoitory'
    required: true
    default: ''
  configuration-path:
    description: 'The path to the configuration file'
    required: false
    default: '.github/config.yml'
runs:
  using: 'node12'
  main: 'dist/index.js'
