on: [push]

jobs:
  pr_labeler:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: PR Validator
        uses: ./ # Uses an action in the root directory
        id: validator
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
