on: [pull_request]

jobs:
  validator:
    runs-on: ubuntu-latest
    name: Labeling and Validation
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run
        uses: ./ # Uses an action in the root directory
        id: validator
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
